// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flexCenter': string;
  'progressiveImage': string;
  'progressiveImagePreloader': string;
}
export const cssExports: CssExports;
export default cssExports;
