// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btnAppear': string;
  'buttonScrollTop': string;
  'scrollToTopWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
