// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'L': string;
  'M': string;
  'S': string;
  'button': string;
  'filled': string;
  'preloader': string;
  'preloader1': string;
  'preloader2': string;
  'preloader3': string;
}
export const cssExports: CssExports;
export default cssExports;
