// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'container': string;
  'contentWrap': string;
  'darkMode': string;
  'error': string;
  'extra': string;
  'floatLabel': string;
  'formWrap': string;
  'headline': string;
  'input': string;
  'loginWrap': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
