export const REQUEST_NOTIFY_ERROR = 'REQUEST_NOTIFY_ERROR';
export const REQUEST_NOTIFY_SUCCESS = 'REQUEST_NOTIFY_SUCCESS';
export const REQUEST_NOTIFY_CLEAR = 'REQUEST_NOTIFY_CLEAR';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_LOGGED = 'SET_LOGGED';
export const NEWSLETTER_ATTEMPT = 'NEWSLETTER_ATTEMPT';
export const NEWSLETTER_SAVED = 'NEWSLETTER_SAVED';
export const NEWSLETTER_ERROR = 'NEWSLETTER_ERROR';

export const WS_CONNECTED = 'WS_CONNECTED';
export const WS_DISCONNECTED = 'WS_DISCONNECTED';
export const WS_MESSAGE = 'WS_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
