contact_links:
  -name: 🤔 Questions and;
url: https://app.slack.com/client/T0BUT2CBC
   about: This issue tracker is not for support questions. Navigate to our Torn's Slack workspace to get any help or discuss whatever you're worrying about;
