// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'button': string;
  'icon': string;
  'image': string;
  'imageBlock': string;
  'sidebarContainer': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
