export const TOGGLE_CHAT = 'TOGGLE_CHAT';
export const SENT_MESSAGE = 'MESSAGE_SENT';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const WRITTING_MESSAGE = 'WRITTING_MESSAGE';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CONNECTION_ERROR = 'CONNECTION_ERROR';
export const SET_NEW_MESSAGES_COUNT = 'SET_NEW_MESSAGES_COUNT';
