// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sidebar': string;
  'toggle': string;
  'toggleChecked': string;
  'toggleScreenreaderOnly': string;
  'toggleThumb': string;
  'toggleTrack': string;
  'toggleTrackCheck': string;
  'toggleTrackX': string;
}
export const cssExports: CssExports;
export default cssExports;
