// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lds-facebook': string;
  'logo': string;
  'preloader': string;
  'preloaderItem': string;
}
export const cssExports: CssExports;
export default cssExports;
