// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'burgerButton': string;
  'burgerContent': string;
  'burgerIconSlice': string;
  'container': string;
  'english': string;
  'extra': string;
  'flag': string;
  'header': string;
  'headerWrap': string;
  'isOpen': string;
  'langContainer': string;
  'language': string;
  'link': string;
  'logo': string;
  'logoWrap': string;
  'mobileMenu': string;
  'mobileMenuOpened': string;
  'navBar': string;
  'russian': string;
  'sticky': string;
  'text': string;
  'ukrainian': string;
}
export const cssExports: CssExports;
export default cssExports;
