// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'cookieWrap': string;
  'link': string;
  'text': string;
  'textWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
