// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'container': string;
  'content': string;
  'cookieWrap': string;
  'extra': string;
  'link': string;
  'text': string;
  'textWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
