// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'bottomContainer': string;
  'clearButton': string;
  'container': string;
  'error': string;
  'errorMessage': string;
  'extra': string;
  'inputContainer': string;
  'inputHelperWrap': string;
  'label': string;
  'lastSearch': string;
  'lastSearches': string;
  'lastSearchesWrap': string;
  'search': string;
  'searchButton': string;
  'searchInput': string;
  'titleSection': string;
  'topContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
