// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorWrap': string;
  'notifywrap': string;
  'successWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
