// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'address': string;
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'bullets': string;
  'companyDescription': string;
  'companyLogo': string;
  'contactsWrap': string;
  'container': string;
  'contentBlock': string;
  'email': string;
  'extra': string;
  'headline': string;
  'icon': string;
  'iconEmail': string;
  'iconTel': string;
  'leftSection': string;
  'link': string;
  'mainContent': string;
  'tel': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
