// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeBtn': string;
  'mainSection': string;
  'sidebar-enter-active': string;
  'sidebar-enter-done': string;
  'sidebar-exit': string;
  'sidebarBlock': string;
  'sidebarWrap': string;
  'topSection': string;
}
export const cssExports: CssExports;
export default cssExports;
