// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'address': string;
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'bullets': string;
  'companyDescription': string;
  'companyLogo': string;
  'container': string;
  'contentBlock': string;
  'copywriting': string;
  'copywritingContent': string;
  'email': string;
  'emailError': string;
  'emailFilled': string;
  'emailSendButton': string;
  'extra': string;
  'footer': string;
  'footerContent': string;
  'icon': string;
  'iconEmail': string;
  'iconFacebook': string;
  'iconInstagram': string;
  'iconTel': string;
  'iconTelegram': string;
  'iconTwitter': string;
  'input': string;
  'labelInput': string;
  'link': string;
  'links': string;
  'newsletter': string;
  'policy': string;
  'rights': string;
  'social': string;
  'tel': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
