// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'blue': string;
  'flatLoader': string;
  'green': string;
  'grey': string;
  'lds-ellipsis1': string;
  'lds-ellipsis2': string;
  'lds-ellipsis3': string;
  'spinnerAnim': string;
  'spinnerCircle': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
