// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aboutUsWrap': string;
  'appFooter': string;
  'appHeader': string;
  'appWrapper': string;
  'body': string;
  'bodyImg': string;
  'companyLogo': string;
  'container': string;
  'extra': string;
  'headline': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
