// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'linkSPA': string;
  'rounded': string;
  'text': string;
  'withBackground': string;
}
export const cssExports: CssExports;
export default cssExports;
