// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonsWrap': string;
  'cancel': string;
  'cell': string;
  'error': string;
  'input': string;
  'mainData': string;
  'newPasswordConfirmRow': string;
  'panel': string;
  'panelsWrap': string;
  'row': string;
  'text': string;
  'textArea': string;
  'textAreaWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
